#!/bin/env bash
PKGNAME=binutils
PKGVER=2.42
LFS=/mnt/lfs
pkgsrc(){
    pushd $LFS/source
if [ ! -f $PKGNAME-$PKGVER.tar.gz ]; then
    wget "https://ftp.kaist.ac.kr/gnu/$PKGNAME/$PKGNAME-$PKGVER.tar.gz"
    wget "https://ftp.kaist.ac.kr/gnu/$PKGNAME/$PKGNAME-$PKGVER.tar.gz.sig"
    gpg --verify "$PKGNAME-$PKGVER.tar.gz.sig" "$PKGNAME-$PKGVER.tar.gz"
fi
    popd
}

build(){
    pushd $LFS/source
    tar -xf "$PKGNAME-$PKGVER.tar.gz"
    cd $PKGNAME-$PKGVER
    mkdir build
    cd build
    ../configure --prefix=$LFS/tools \
             --with-sysroot=$LFS \
             --target=$LFS_TGT   \
             --disable-nls       \
             --enable-gprofng=no \
             --disable-werror    \
             --enable-default-hash-style=gnu
    make -j24
    make DESTDIR="$LFS/build/$PKGNAME-$PKGVER" install
    popd
}

postbuild(){
    pushd $LFS/source
    rm -rf "$PKGNAME-$PKGVER.tar.gz" "$PKGNAME-$PKGVER.tar.gz.sig" "$PKGNAME-$PKGVER"
    pushd "$LFS/build/$PKGNAME-$PKGVER/$LFS/"
    rmv tools /mnt/lfs/tools
    popd
    popd
}
pkgsrc
build
postbuild
