#!/bin/env bash
PKGNAME=gcc
PKGVER=13.2.0
LFS=/mnt/lfs
DEFPKG=(mpfr gmp mpc)
DEFVER=(4.2.1 6.3.0 1.3.1)
LENGTH=${#DEFPKG[@]}
pkgsrc(){
    pushd $LFS/source
if [ ! -f $PKGNAME-$PKGVER.tar.gz ]; then
    wget "https://ftp.kaist.ac.kr/gnu/$PKGNAME/$PKGNAME-$PKGVER/$PKGNAME-$PKGVER.tar.gz"
    wget "https://ftp.kaist.ac.kr/gnu/$PKGNAME/$PKGNAME-$PKGVER/$PKGNAME-$PKGVER.tar.gz.sig"
    gpg --verify "$PKGNAME-$PKGVER.tar.gz.sig" "$PKGNAME-$PKGVER.tar.gz"
    tar -xf "$PKGNAME-$PKGVER.tar.gz"
fi
for ((i=0;i<LENGTH;i++)); do
    DEFNAME=${DEFPKG[i]}
    DEFVER=${DEFVER[i]}
    if [ ! -f $DEFNAME-$DEFVER.tar.gz ]; then
        wget "https://ftp.kaist.ac.kr/gnu/$DEFNAME/$DEFNAME-$DEFVER.tar.gz"
        wget "https://ftp.kaist.ac.kr/gnu/$DEFNAME/$DEFNAME-$DEFVER.tar.gz.sig"
        gpg --verify "$DEFNAME-$DEFVER.tar.gz.sig" "$DEFNAME-$DEFVER.tar.gz"
        tar -xf "$DEFNAME-$DEFVER.tar.gz"
        mv "$DEFNAME-$DEFVER" "$PKGNAME-$PKGVER/$DEFNAME"
        rm "$DEFNAME-$DEFVER.tar.gz.sig" "$DEFNAME-$DEFVER.tar.gz"
    fi
done
    popd
}

build(){
    pushd "$LFS/source/$PKGNAME-$PKGVER"
    sed '/thread_header =/s/@.*@/gthr-posix.h/' \
    -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in
    mkdir build
    cd build
    ../configure                                   \
    --build=$(../config.guess)                     \
    --host=$LFS_TGT                                \
    --target=$LFS_TGT                              \
    LDFLAGS_FOR_TARGET=-L$PWD/$LFS_TGT/libgcc      \
    --prefix=/usr                                  \
    --with-build-sysroot=$LFS                      \
    --enable-default-pie                           \
    --enable-default-ssp                           \
    --disable-nls                                  \
    --disable-multilib                             \
    --disable-libatomic                            \
    --disable-libgomp                              \
    --disable-libquadmath                          \
    --disable-libsanitizer                         \
    --disable-libssp                               \
    --disable-libvtv                               \
    --enable-languages=c,c++
    make -j24
    make DESTDIR="$LFS/build/$PKGNAME-$PKGVER-post" install
    popd
}

postbuild(){
    pushd $LFS/source
    rm -rf "$PKGNAME-$PKGVER.tar.gz" "$PKGNAME-$PKGVER" "$PKGNAME-$PKGVER.tar.gz.sig"
    pushd "$LFS/build"
    rmv "$PKGNAME-$PKGVER-post" $LFS
    ln -sv gcc $LFS/usr/bin/cc
    popd
    popd
}
pkgsrc
build
postbuild
